language: java

sudo: false

before_install:
 #- wget -q -O - http://get.redstonelamp.net/travis/before_install.sh | bash
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - cd $TRAVIS_BUILD_DIR
  #- echo "buildNum=$TRAVIS_BUILD_NUMBER" > src/main/resources/buildInformation.properties
  #- echo "buildCommit=$TRAVIS_COMMIT" >> src/main/resources/buildInformation.properties
  #- echo "buildDate=$DATE" >> src/main/resources/buildInformation.properties

install: echo "Dummy thing to prevent travis from doing strange maven thing."

script: 'mvn license:check package | egrep "\\[(INFO|WARNING)\\]"'

after_success:
  - cd $TRAVIS_BUILD_DIR
  - wget -O webpush.py http://get.redstonelamp.net/travis/webpush.py
  - python webpush.py
  #- wget -q -O - http://get.redstonelamp.net/travis/after_success.sh | bash

after_failure:
  - echo "Build failed! Not uploading JAR"

jdk:
  - oraclejdk8

env:
  global:
    - secure: "hCuzV3SC/GZ9dr3D24libYU5N3xYn3cLwIhXdOFcuQ7BSKErN9cEBkqLGs1RSrKaEfJrs
GjRfjjKlD+FQ6LwTt9um2fVt0i+Lb1XeQpFyMTRICoo86eewdGYlqiuWZTGbnpbur20nJLtiQYdYmk0J
yX1fr6k6VyHhJt+5L15z4A="
    - secure: "HNyuHhKNpeYs/2A0OXmPGNw79j1yOKU2lUhho4zmfPSzeLUfZh5N5gt0a/G5TlG2TICIv
xSPJRrf5R6OmTJMeMLEYzScaiAuGHgvDGMVs+ZPngCvnwSDIgQ6hwqBnnDEd5vTSyHQQIjUtw+1LTxwp
0jZCN39cUYl9gvsH1mxnks="
    - rlVersion="1.2.0"
    - mcpeVersion="0.12.1"
    - mcpcVersion="15w35e"
    - stability="DEV"
    - DATE='date +%Y-%m-%d:%H:%M:%S'
